NOISSUE Fix typo and remove SSH URL
MultiMC/MultiMC5 pull request #3903
Opened 2021-06-26 01:16 UTC by Sebastian-byte

Many will not be capable of using the SSH URL, because this requires a SSH key.

2021-06-26 14:50 UTC, spannerman79 requested changes

2021-06-26 15:01 UTC, phit commented on BUILD.md
> -git clone git@github.com:MultiMC/MultiMC5.git
what? how does that solve that? All the other Git commands on the same page already use the https variant, its also the default when you click the clone button on GitHub

2021-06-27 07:48 UTC, AverageComet250 commented on BUILD.md
> -git clone git@github.com:MultiMC/MultiMC5.git
I agree with @Sebastian-byte and @phit. https URLs are more Accessible and thus a better option

2021-06-27 07:48 UTC, AverageComet250 approved these changes

2021-06-27 10:36 UTC, jamierocks commented on BUILD.md
> -git clone git@github.com:MultiMC/MultiMC5.git
How are they more accessible?

2021-06-27 13:13 UTC, Janrupf commented on BUILD.md
> -git clone git@github.com:MultiMC/MultiMC5.git
I don't think it really matters, but given that the MultiMC repository uses `https` for submodules anyway, the instructions in the documentation may as well hint using `https`. Anyone with some git knowledge will swap them anyway, and for convenience just being able to copy the clone command without an SSH key seems reasonable.

2021-07-22 15:41 UTC, merged