Stop application freezes on macOS by moving data to MultiMC.app/Data
MultiMC/MultiMC5 pull request #3919
Opened 2021-07-02 01:52 UTC by hamarb123

Fixes #3081
Fixes #2529
This is a continuation of PR #3081 which has a dialogue on the first launch that asks the user if they want to move and explains some of the benefits and drawbacks. It also adds a button in the settings menu that allows the user to move the data at a later date if they say no initially. If a user selects no, the dialogue doesn't show up again and they can change their option with the setting. There is no way to move the data back through an interface, but the user could move contents of `MultiMC.app/Data` to `MultiMC.app/Contents/MacOS`. On the initial launch, it chooses the new location by default, without prompt.
No translations have been added at the moment because I do not know how to add them.

2021-07-02 01:54 UTC, hamarb123 commented
I've tested it with my massive folder and it works. Not sure if the folders list are up to date or not, it's just what was in #3081.

2021-07-02 03:15 UTC, Ghalid requested changes
Great work!

By the way, MultiMC usually prefers that commit messages start with the issue they are meant to fix. So in this case, commit messages should take the form of "GH-2529 [COMMIT MESSAGE]".

I don't have any comments about the code, but I have some suggestions about the messages.

2021-07-02 03:15 UTC, Ghalid commented on application/pages/global/MultiMCPage.ui
> +          <string>Move MultiMC data to new location (requires restart, will happen automatically)</string>
```suggestion
          <string>Move MultiMC data to new location (will restart MultiMC)</string>
```
A little clearer?

2021-07-02 03:59 UTC, hamarb123 commented on application/MultiMC.cpp
> +            askMoveDialogue = QMessageBox::question(nullptr, "MultiMC 5", "Would you like to move application data to a new data location? It will improve performance in some ways (eg. launch, open m
I will fix it, Qt automatically makes it multi-line:
![image](https://user-images.githubusercontent.com/25316035/124218499-aa34b100-db3d-11eb-9195-ca583c9c3eb5.png)

2021-07-02 04:06 UTC, hamarb123 commented on application/MultiMC.cpp
> +            askMoveDialogue = QMessageBox::question(nullptr, "MultiMC 5", "Would you like to move application data to a new data location? It will improve performance in some ways (eg. launch, open m
Is the new message clearer (just committed)?

2021-07-02 04:19 UTC, Ghalid commented on application/MultiMC.cpp
> +            askMoveDialogue = QMessageBox::question(nullptr, "MultiMC 5", "Would you like to move application data to a new data location? It will improve performance in some ways (eg. launch, open m
Looks good to me! 👍

2021-07-02 04:20 UTC, hamarb123 commented on application/MultiMC.cpp
> +            askMoveDialogue = QMessageBox::question(nullptr, "MultiMC 5", "Would you like to move application data to a new data location? It will improve performance in some ways (eg. launch, open m
Thanks!

2021-07-10 23:17 UTC, Zetabite commented
Since peterix will sooner or later write it himself: "squash commits and use the proper commit message prefixes"

2021-07-10 23:19 UTC, hamarb123 commented
I can work out how to do that, what's the proper commit message prefix format so I don't do it wrong?

2021-07-10 23:20 UTC, Zetabite commented
Plenty of examples in the closed PRs

2021-07-10 23:38 UTC, hamarb123 commented
Can you check that the squash commit does this all correctly? Thanks!

2021-07-10 23:45 UTC, Zetabite commented
Looks definetly a lot better and cleaner, now peterix and co can easily skim through it and evaluate it

2021-07-12 12:58 UTC, magicus reviewed
FWIW the patch looks good to me. I'm a mac user suffering from this issue, and this sounds like a very sensible solution to the problem.

2021-07-22 19:26 UTC, Boundarybreaker commented
...would it be possible to move everything to `~/Library/Application Support/MultiMC`? That's where you'd normally find stuff like this - that's where Minecraft, Steam, and basically every other launcher put their game data.

2021-07-22 20:42 UTC, Chew commented
Was shot down because it would violate the "portable" design of the project. You'd need to move stuff there manually.

2021-07-22 20:44 UTC, Boundarybreaker commented
...what do you mean by "portable" here, easy to port to other platforms or you can move it around? neither definition makes sense with that explanation

2021-07-22 20:47 UTC, jamierocks commented
the [normal meaning](https://en.wikipedia.org/wiki/Portable_application). basically that the application is self-contained and can be moved between systems easily.

2021-07-22 20:48 UTC, Boundarybreaker commented
I see...

2021-07-22 21:10 UTC, hamarb123 commented
> I see...

It means you can copy the .app onto a usb and use it on different macs with all of the data included.
Personally, I would opt for `~/Library/Application Support/MultiMC` because I think most users would expect user data to be in user data and would probably not copy any .apps when moving to a new computer (since for many apps it's not recommended). My main issue with putting it in a .app is it's almost impossible to select anything in a dialogue (eg. speedrun timer), you have to copy the path and hope it will paste when pressing Shift+Command+G.
But it is fine how it currently is and I think portability is a good thing to have. If @peterix is okay with `~/Library/Application Support/MultiMC` then it can be changed to be there (it's what I'd personally prefer), so ask him, but I assume he'd say that inside the app bundle is better.

2021-07-23 13:14 UTC, peterix commented
It's not strictly better. It's different.

It can also potentially be on a different drive, and would need more code to handle that eventuality.

Changing this abruptly would also mess things up for people who expect the current behavior and want it that way. It's way easier to do things like this from scratch instead of changing them later.

The long term thing would be to make 'portable' mode not the default.
For example, the application could look at its own name (exe name on WIndows, .app name on macOS, binary name on Linux) and if it has 'portable' in it, run in portable mode. Otherwise, use the appropriate system locations for data.

Still, how do you go seamlessly from the current state to the new one? If I just push it in an update, and it's not damn near perfect, people's stuff will get messed up.

This PR doesn't seem to introduce any of these issues, so it's way easier to merge than something that would address the above.

2021-07-23 14:13 UTC, merged

2021-07-23 14:14 UTC, peterix commented
Merging to make the CI make me builds I can test...

2021-07-23 14:48 UTC, peterix commented
Seems to be working quite well.